//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correlativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Correlativo()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int IdCorrelativo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string NombreTabla { get; set; }
        public string Abreviatura { get; set; }
        public string Serie { get; set; }
        public Nullable<int> NroCorrelativo { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
