//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento()
        {
            this.MovimientoDetalle = new HashSet<MovimientoDetalle>();
        }
    
        public int IdMovimiento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTipoMovimiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string NroDocumento { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoDetalle> MovimientoDetalle { get; set; }
    }
}
