//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int IdVentaDetalle { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
