//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librería.Desktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdEntidad { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdCorrelativo { get; set; }
        public string Correlativo { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Correlativo Correlativo1 { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
